variables:
  conda.deps: >
    python=$(python.version)
    pandas numpy scipy fastparquet python-snappy numba cffi pyarrow joblib
    invoke coverage pytest pytest-cov pytest-doctestplus cython dask distributed
  pip.deps: >
    invoke pytest coverage pytest-cov pytest-doctestplus
    pandas scipy pyarrow numpy joblib
    numba cython cffi

jobs:

- template: build-support/test-linux-conda.yml
- template: build-support/test-linux-vanilla.yml
- template: build-support/test-odd-environs.yml
- template: build-support/test-windows-vanilla.yml
- template: build-support/test-windows-conda.yml
- template: build-support/test-mac-conda.yml
- template: build-support/publish.yml
