channels:
  - conda-forge
  - pytorch
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - sphinx >=4.2
  - sphinxext-opengraph >=0.5
  - sphinxcontrib-bibtex >=2.0
  - pydata-sphinx-theme >=0.15.4
  - myst-nb >=0.13
  - just
  - pytorch-cpu
  - nomkl
  - pandas >=1.5,<3
  - numpy >=1.23,<2
  - scipy >=1.9.0
  - pytorch >=2.1,<3
  - threadpoolctl >=3.0
  - pydantic <3,>=2.8
  - scikit-learn >=1.1
  - numba >=0.56
  - implicit >=0.6.1
  - hpfrec ==0.2.*
  - pip:
      - seedbank>=0.2.0a2
      - progress-api>=0.1.0a9
      - manylog>=0.1.0a5
